# Generated by Django 4.2.7 on 2025-10-05 16:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tccs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('resumo', models.TextField(blank=True, null=True, verbose_name='Resumo')),
                ('etapa_atual', models.CharField(choices=[('INICIALIZACAO', 'Inicialização'), ('DESENVOLVIMENTO', 'Desenvolvimento'), ('FORMACAO_BANCA_FASE_1', 'Formação de Banca - Fase 1'), ('AVALIACAO_FASE_1', 'Avaliação - Fase 1'), ('VALIDACAO_FASE_1', 'Validação - Fase 1'), ('AGENDAMENTO_APRESENTACAO', 'Agendamento da Apresentação'), ('APRESENTACAO_FASE_2', 'Apresentação - Fase 2'), ('ANALISE_FINAL_COORDENADOR', 'Análise Final do Coordenador'), ('AGUARDANDO_AJUSTES_FINAIS', 'Aguardando Ajustes Finais'), ('CONCLUIDO', 'Concluído'), ('DESCONTINUADO', 'Descontinuado'), ('REPROVADO_FASE_1', 'Reprovado - Fase 1'), ('REPROVADO_FASE_2', 'Reprovado - Fase 2')], default='INICIALIZACAO', max_length=50, verbose_name='Etapa Atual')),
                ('semestre', models.CharField(help_text='Ex: 2025.1', max_length=20, verbose_name='Semestre')),
                ('flag_continuidade', models.BooleanField(default=False, help_text='Orientador aprovou continuidade', verbose_name='Flag de Continuidade')),
                ('flag_liberado_avaliacao', models.BooleanField(default=False, help_text='Orientador liberou para formar banca', verbose_name='Flag Liberado para Avaliação')),
                ('avaliacao_fase1_bloqueada', models.BooleanField(default=False, help_text='Coordenador bloqueou edições para análise', verbose_name='Avaliação Fase 1 Bloqueada')),
                ('coorientador_nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Coorientador')),
                ('coorientador_titulacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulação do Coorientador')),
                ('coorientador_afiliacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Afiliação do Coorientador')),
                ('coorientador_lattes', models.URLField(blank=True, null=True, verbose_name='Lattes do Coorientador')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo_usuario': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='tccs_como_aluno', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('coorientador', models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario__in': ['PROFESSOR', 'COORDENADOR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tccs_como_coorientador', to=settings.AUTH_USER_MODEL, verbose_name='Coorientador')),
                ('orientador', models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario__in': ['PROFESSOR', 'COORDENADOR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tccs_como_orientador', to=settings.AUTH_USER_MODEL, verbose_name='Orientador')),
            ],
            options={
                'verbose_name': 'TCC',
                'verbose_name_plural': 'TCCs',
                'ordering': ['-criado_em'],
                'unique_together': {('aluno', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoOrientacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem do Aluno')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('resposta_professor', models.TextField(blank=True, null=True, verbose_name='Resposta do Professor')),
                ('coorientador_nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Coorientador')),
                ('coorientador_titulacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulação')),
                ('coorientador_afiliacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Afiliação')),
                ('coorientador_lattes', models.URLField(blank=True, null=True, verbose_name='Link Lattes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('respondido_em', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('professor', models.ForeignKey(limit_choices_to={'tipo_usuario__in': ['PROFESSOR', 'COORDENADOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
                ('tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='tccs.tcc', verbose_name='TCC')),
            ],
            options={
                'verbose_name': 'Solicitação de Orientação',
                'verbose_name_plural': 'Solicitações de Orientação',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CRIACAO_TCC', 'Criação do TCC'), ('SOLICITACAO_ENVIADA', 'Solicitação Enviada'), ('SOLICITACAO_ACEITA', 'Solicitação Aceita'), ('SOLICITACAO_RECUSADA', 'Solicitação Recusada'), ('SOLICITACAO_CANCELADA', 'Solicitação Cancelada'), ('UPLOAD_DOCUMENTO', 'Upload de Documento'), ('FEEDBACK_ORIENTADOR', 'Feedback do Orientador'), ('APROVACAO_CONTINUIDADE', 'Aprovação de Continuidade'), ('REPROVACAO_CONTINUIDADE', 'Reprovação de Continuidade'), ('LIBERACAO_AVALIACAO', 'Liberação para Avaliação'), ('FORMACAO_BANCA', 'Formação de Banca'), ('AVALIACAO_ENVIADA', 'Avaliação Enviada'), ('VALIDACAO_COORDENADOR', 'Validação do Coordenador'), ('AGENDAMENTO_DEFESA', 'Agendamento de Defesa'), ('DEFESA_REALIZADA', 'Defesa Realizada'), ('AJUSTES_SOLICITADOS', 'Ajustes Solicitados'), ('CONCLUSAO', 'Conclusão'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('detalhes_json', models.JSONField(blank=True, null=True, verbose_name='Detalhes')),
                ('visibilidade', models.CharField(choices=[('TODOS', 'Visível para Todos'), ('ORIENTADOR_COORDENADOR', 'Orientador e Coordenador'), ('COORDENADOR_APENAS', 'Apenas Coordenador')], default='TODOS', max_length=30, verbose_name='Visibilidade')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='tccs.tcc', verbose_name='TCC')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário que gerou o evento (null se automático)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Evento da Timeline',
                'verbose_name_plural': 'Eventos da Timeline',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoTCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('PLANO_DESENVOLVIMENTO', 'Plano de Desenvolvimento'), ('TERMO_ACEITE', 'Termo de Aceite'), ('MONOGRAFIA', 'Monografia'), ('APRESENTACAO', 'Apresentação'), ('ATA', 'Ata'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Documento')),
                ('arquivo', models.FileField(upload_to=tccs.models.upload_documento_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), tccs.models.validar_tamanho_arquivo], verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('tamanho', models.IntegerField(verbose_name='Tamanho (bytes)')),
                ('versao', models.IntegerField(default=1, verbose_name='Versão')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='tccs.tcc', verbose_name='TCC')),
            ],
            options={
                'verbose_name': 'Documento do TCC',
                'verbose_name_plural': 'Documentos do TCC',
                'ordering': ['-criado_em'],
            },
        ),
    ]
