# Generated by Django 4.2.7 on 2025-10-12 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tccs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoRecusa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer', models.TextField(verbose_name='Parecer do Coordenador')),
                ('coordenador_nome', models.CharField(max_length=255, verbose_name='Nome do Coordenador')),
                ('recusado_em', models.DateTimeField(auto_now_add=True, verbose_name='Recusado em')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historico_recusa', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recusas_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador')),
            ],
            options={
                'verbose_name': 'Histórico de Recusa',
                'verbose_name_plural': 'Históricos de Recusa',
                'ordering': ['-recusado_em'],
            },
        ),
    ]
