# Generated by Django migration

from django.db import migrations


def aprovar_documentos_iniciais(apps, schema_editor):
    """
    Atualiza todos os documentos iniciais (PLANO_DESENVOLVIMENTO e TERMO_ACEITE)
    existentes para status APROVADO, limpando feedback.
    """
    DocumentoTCC = apps.get_model('tccs', 'DocumentoTCC')

    DocumentoTCC.objects.filter(
        tipo_documento__in=['PLANO_DESENVOLVIMENTO', 'TERMO_ACEITE']
    ).update(
        status='APROVADO',
        feedback=''
    )


def restaurar_status_documentos(apps, schema_editor):
    """
    Função reversa: volta documentos iniciais para PENDENTE.
    (Opcional - pode não ser necessário reverter na prática)
    """
    DocumentoTCC = apps.get_model('tccs', 'DocumentoTCC')

    DocumentoTCC.objects.filter(
        tipo_documento__in=['PLANO_DESENVOLVIMENTO', 'TERMO_ACEITE']
    ).update(
        status='PENDENTE'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tccs', '0002_historicorecusa'),
    ]

    operations = [
        migrations.RunPython(aprovar_documentos_iniciais, restaurar_status_documentos),
    ]
