# Generated by Django 4.2.7 on 2025-10-13 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tccs', '0003_auto_aprova_documentos_iniciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcc',
            name='liberacoes_atualizadas_em',
            field=models.DateTimeField(blank=True, help_text='Data da última alteração manual de prazos', null=True, verbose_name='Liberações atualizadas em'),
        ),
        migrations.AddField(
            model_name='tcc',
            name='liberacoes_atualizadas_por',
            field=models.ForeignKey(blank=True, help_text='Coordenador que alterou as liberações', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liberacoes_tcc_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Liberações atualizadas por'),
        ),
        migrations.AddField(
            model_name='tcc',
            name='liberar_ajustes_finais',
            field=models.BooleanField(default=False, help_text='Permite enviar ajustes fora do prazo', verbose_name='Liberar Ajustes Finais'),
        ),
        migrations.AddField(
            model_name='tcc',
            name='liberar_continuidade',
            field=models.BooleanField(default=False, help_text='Permite confirmar continuidade fora do prazo', verbose_name='Liberar confirmação de continuidade'),
        ),
        migrations.AddField(
            model_name='tcc',
            name='liberar_defesas',
            field=models.BooleanField(default=False, help_text='Permite registrar defesas fora do prazo', verbose_name='Liberar Período de Defesas'),
        ),
        migrations.AddField(
            model_name='tcc',
            name='liberar_desenvolvimento',
            field=models.BooleanField(default=False, help_text='Libera envio e avaliação de monografia fora do prazo', verbose_name='Liberar fase de desenvolvimento'),
        ),
        migrations.AddField(
            model_name='tcc',
            name='liberar_envio_documentos',
            field=models.BooleanField(default=False, help_text='Quando True, ignora o prazo do calendário para documentos iniciais', verbose_name='Liberar envio de documentos iniciais'),
        ),
        migrations.AddField(
            model_name='tcc',
            name='liberar_fase1',
            field=models.BooleanField(default=False, help_text='Permite ações da Fase I fora do prazo', verbose_name='Liberar Avaliação Fase I'),
        ),
        migrations.AlterField(
            model_name='documentotcc',
            name='tipo_documento',
            field=models.CharField(choices=[('PLANO_DESENVOLVIMENTO', 'Plano de Desenvolvimento'), ('TERMO_ACEITE', 'Termo de Aceite'), ('MONOGRAFIA', 'Monografia'), ('TERMO_SOLICITACAO_AVALIACAO', 'Termo de Solicitação de Avaliação'), ('APRESENTACAO', 'Apresentação'), ('ATA', 'Ata'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Documento'),
        ),
    ]
