# Generated by Django 4.2.7 on 2025-10-15 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tccs', '0004_tcc_liberacoes_atualizadas_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancaFase1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('COMPLETA', 'Completa')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_formacao', models.DateTimeField(blank=True, help_text='Data em que a banca foi concluída', null=True, verbose_name='Data de Formação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('formada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bancas_formadas', to=settings.AUTH_USER_MODEL, verbose_name='Formada por')),
                ('tcc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banca_fase1', to='tccs.tcc', verbose_name='TCC')),
            ],
            options={
                'verbose_name': 'Banca Fase I',
                'verbose_name_plural': 'Bancas Fase I',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MembroBanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ORIENTADOR', 'Orientador'), ('AVALIADOR', 'Avaliador'), ('SUPLENTE', 'Suplente')], max_length=20, verbose_name='Tipo')),
                ('indicado_por', models.CharField(choices=[('ORIENTADOR', 'Orientador'), ('COORDENADOR', 'Coordenador')], max_length=20, verbose_name='Indicado por')),
                ('ordem', models.IntegerField(help_text='Ordem de apresentação', verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='tccs.bancafase1', verbose_name='Banca')),
                ('usuario', models.ForeignKey(limit_choices_to={'tipo_usuario__in': ['PROFESSOR', 'COORDENADOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_banca', to=settings.AUTH_USER_MODEL, verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Membro de Banca',
                'verbose_name_plural': 'Membros de Banca',
                'ordering': ['banca', 'ordem'],
                'unique_together': {('banca', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoFase1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_conteudo', models.DecimalField(blank=True, decimal_places=2, help_text='Nota de 0 a 10', max_digits=4, null=True, verbose_name='Nota de Conteúdo')),
                ('nota_metodologia', models.DecimalField(blank=True, decimal_places=2, help_text='Nota de 0 a 10', max_digits=4, null=True, verbose_name='Nota de Metodologia')),
                ('nota_apresentacao', models.DecimalField(blank=True, decimal_places=2, help_text='Nota de 0 a 10', max_digits=4, null=True, verbose_name='Nota de Apresentação')),
                ('parecer', models.TextField(blank=True, null=True, verbose_name='Parecer')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('BLOQUEADO', 'Bloqueado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('avaliador', models.ForeignKey(limit_choices_to={'tipo_usuario__in': ['PROFESSOR', 'COORDENADOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_fase1', to='tccs.tcc', verbose_name='TCC')),
            ],
            options={
                'verbose_name': 'Avaliação Fase I',
                'verbose_name_plural': 'Avaliações Fase I',
                'ordering': ['-criado_em'],
                'unique_together': {('tcc', 'avaliador')},
            },
        ),
    ]
