# Generated by Django 4.2.7 on 2025-10-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tccs', '0005_bancafase1_membrobanca_avaliacaofase1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventotimeline',
            name='tipo_evento',
            field=models.CharField(choices=[('CRIACAO_TCC', 'Criação do TCC'), ('SOLICITACAO_ENVIADA', 'Solicitação Enviada'), ('SOLICITACAO_ACEITA', 'Solicitação Aceita'), ('SOLICITACAO_RECUSADA', 'Solicitação Recusada'), ('SOLICITACAO_CANCELADA', 'Solicitação Cancelada'), ('UPLOAD_DOCUMENTO', 'Upload de Documento'), ('FEEDBACK_ORIENTADOR', 'Feedback do Orientador'), ('APROVACAO_CONTINUIDADE', 'Aprovação de Continuidade'), ('REPROVACAO_CONTINUIDADE', 'Reprovação de Continuidade'), ('LIBERACAO_AVALIACAO', 'Liberação para Avaliação'), ('FORMACAO_BANCA', 'Formação de Banca'), ('AVALIACAO_ENVIADA', 'Avaliação Enviada'), ('AVALIACAO_REABERTA', 'Avaliação Reaberta'), ('BLOQUEIO_AVALIACOES', 'Bloqueio de Avaliações'), ('DESBLOQUEIO_AVALIACOES', 'Desbloqueio de Avaliações'), ('SOLICITACAO_AJUSTES', 'Solicitação de Ajustes'), ('APROVACAO_PARCIAL', 'Aprovação Parcial'), ('RESULTADO_FASE_1', 'Resultado da Fase I'), ('VALIDACAO_COORDENADOR', 'Validação do Coordenador'), ('AGENDAMENTO_DEFESA', 'Agendamento de Defesa'), ('DEFESA_REALIZADA', 'Defesa Realizada'), ('AJUSTES_SOLICITADOS', 'Ajustes Solicitados'), ('CONCLUSAO', 'Conclusão'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='membrobanca',
            name='tipo',
            field=models.CharField(choices=[('ORIENTADOR', 'Orientador'), ('AVALIADOR', 'Avaliador')], max_length=20, verbose_name='Tipo'),
        ),
    ]
