# Generated by Django 4.2.7 on 2025-10-16 05:06

from django.db import migrations, models
import django.db.models.deletion
import tccs.models


class Migration(migrations.Migration):

    dependencies = [
        ('tccs', '0006_alter_eventotimeline_tipo_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancafase1',
            name='documento_avaliacao',
            field=models.ForeignKey(blank=True, help_text='Monografia anônima para avaliação duplo-cega. Se não especificado, usa a monografia original.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banca_avaliacao', to='tccs.documentotcc', verbose_name='Documento para Avaliação'),
        ),
        migrations.AlterField(
            model_name='documentotcc',
            name='arquivo',
            field=models.FileField(upload_to=tccs.models.upload_documento_path, validators=[tccs.models.validar_extensao_documento, tccs.models.validar_tamanho_arquivo], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='documentotcc',
            name='tipo_documento',
            field=models.CharField(choices=[('PLANO_DESENVOLVIMENTO', 'Plano de Desenvolvimento'), ('TERMO_ACEITE', 'Termo de Aceite'), ('MONOGRAFIA', 'Monografia'), ('MONOGRAFIA_AVALIACAO', 'Monografia para Avaliação (Anônima)'), ('TERMO_SOLICITACAO_AVALIACAO', 'Termo de Solicitação de Avaliação'), ('APRESENTACAO', 'Apresentação'), ('ATA', 'Ata'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Documento'),
        ),
    ]
