# Generated by Django 4.2.7 on 2025-10-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tccs', '0007_adicionar_documento_avaliacao_banca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaofase1',
            name='nota_apresentacao',
        ),
        migrations.RemoveField(
            model_name='avaliacaofase1',
            name='nota_conteudo',
        ),
        migrations.RemoveField(
            model_name='avaliacaofase1',
            name='nota_metodologia',
        ),
        migrations.AddField(
            model_name='avaliacaofase1',
            name='nota_conclusoes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nota de 0 até o peso configurado (padrão: 1.5)', max_digits=4, null=True, verbose_name='Nota - Conclusões'),
        ),
        migrations.AddField(
            model_name='avaliacaofase1',
            name='nota_desenvolvimento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nota de 0 até o peso configurado (padrão: 3.5)', max_digits=4, null=True, verbose_name='Nota - Desenvolvimento'),
        ),
        migrations.AddField(
            model_name='avaliacaofase1',
            name='nota_introducao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nota de 0 até o peso configurado (padrão: 2.0)', max_digits=4, null=True, verbose_name='Nota - Introdução/Relevância'),
        ),
        migrations.AddField(
            model_name='avaliacaofase1',
            name='nota_resumo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nota de 0 até o peso configurado (padrão: 1.0)', max_digits=4, null=True, verbose_name='Nota - Resumo'),
        ),
        migrations.AddField(
            model_name='avaliacaofase1',
            name='nota_revisao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nota de 0 até o peso configurado (padrão: 2.0)', max_digits=4, null=True, verbose_name='Nota - Revisão Bibliográfica'),
        ),
    ]
