# Generated by Django 4.2.7 on 2025-10-18 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tccs', '0008_atualizar_avaliacaofase1_cinco_criterios'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoDefesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data agendada para a apresentação', verbose_name='Data da Defesa')),
                ('hora', models.TimeField(help_text='Horário agendado para a apresentação', verbose_name='Horário da Defesa')),
                ('local', models.CharField(help_text='Sala, auditório ou link online', max_length=200, verbose_name='Local da Defesa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agendado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defesas_agendadas', to=settings.AUTH_USER_MODEL, verbose_name='Agendado por')),
                ('tcc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agendamento_defesa', to='tccs.tcc', verbose_name='TCC')),
            ],
            options={
                'verbose_name': 'Agendamento de Defesa',
                'verbose_name_plural': 'Agendamentos de Defesa',
                'ordering': ['-criado_em'],
            },
        ),
    ]
