# Generated by Django 4.2.7 on 2025-10-18 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tccs', '0009_agendamentodefesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoFase2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_coerencia_conteudo', models.DecimalField(blank=True, decimal_places=2, help_text='Coerência do conteúdo da apresentação oral com o documento textual (padrão: 2.0)', max_digits=4, null=True, verbose_name='Nota - Coerência do Conteúdo')),
                ('nota_qualidade_apresentacao', models.DecimalField(blank=True, decimal_places=2, help_text='Qualidade e estrutura do material de apresentação (padrão: 2.0)', max_digits=4, null=True, verbose_name='Nota - Qualidade e Estrutura da Apresentação')),
                ('nota_dominio_tema', models.DecimalField(blank=True, decimal_places=2, help_text='Domínio e conhecimento do tema (padrão: 2.5)', max_digits=4, null=True, verbose_name='Nota - Domínio e Conhecimento do Tema')),
                ('nota_clareza_fluencia', models.DecimalField(blank=True, decimal_places=2, help_text='Clareza e fluência verbal na exposição de ideias (padrão: 2.5)', max_digits=4, null=True, verbose_name='Nota - Clareza e Fluência Verbal')),
                ('nota_observancia_tempo', models.DecimalField(blank=True, decimal_places=2, help_text='Observância do tempo de apresentação (padrão: 1.0)', max_digits=4, null=True, verbose_name='Nota - Observância do Tempo de Apresentação')),
                ('parecer', models.TextField(blank=True, null=True, verbose_name='Comentários (facultativo)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('BLOQUEADO', 'Bloqueado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('avaliador', models.ForeignKey(limit_choices_to={'tipo_usuario__in': ['PROFESSOR', 'COORDENADOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_fase2_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_fase2', to='tccs.tcc', verbose_name='TCC')),
            ],
            options={
                'verbose_name': 'Avaliação Fase II',
                'verbose_name_plural': 'Avaliações Fase II',
                'ordering': ['-criado_em'],
                'unique_together': {('tcc', 'avaliador')},
            },
        ),
    ]
