# Generated by Django 4.2.7 on 2025-10-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tccs', '0010_criar_avaliacaofase2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcc',
            name='avaliacao_fase2_bloqueada',
            field=models.BooleanField(default=False, help_text='Coordenador bloqueou edições para análise', verbose_name='Avaliação Fase 2 Bloqueada'),
        ),
        migrations.AddField(
            model_name='tcc',
            name='liberar_fase2',
            field=models.BooleanField(default=False, help_text='Permite ações da Fase II fora do prazo', verbose_name='Liberar Avaliação Fase II'),
        ),
    ]
