# Generated by Django 4.2.7 on 2025-10-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tccs', '0011_adicionar_controles_fase2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventotimeline',
            name='tipo_evento',
            field=models.CharField(choices=[('CRIACAO_TCC', 'Criação do TCC'), ('SOLICITACAO_ENVIADA', 'Solicitação Enviada'), ('SOLICITACAO_ACEITA', 'Solicitação Aceita'), ('SOLICITACAO_RECUSADA', 'Solicitação Recusada'), ('SOLICITACAO_CANCELADA', 'Solicitação Cancelada'), ('UPLOAD_DOCUMENTO', 'Upload de Documento'), ('FEEDBACK_ORIENTADOR', 'Feedback do Orientador'), ('APROVACAO_CONTINUIDADE', 'Aprovação de Continuidade'), ('REPROVACAO_CONTINUIDADE', 'Reprovação de Continuidade'), ('LIBERACAO_AVALIACAO', 'Liberação para Avaliação'), ('FORMACAO_BANCA', 'Formação de Banca'), ('AVALIACAO_ENVIADA', 'Avaliação Enviada'), ('AVALIACAO_REABERTA', 'Avaliação Reaberta'), ('BLOQUEIO_AVALIACOES', 'Bloqueio de Avaliações'), ('DESBLOQUEIO_AVALIACOES', 'Desbloqueio de Avaliações'), ('SOLICITACAO_AJUSTES', 'Solicitação de Ajustes'), ('APROVACAO_PARCIAL', 'Aprovação Parcial'), ('RESULTADO_FASE_1', 'Resultado da Fase I'), ('RESULTADO_FINAL', 'Resultado Final'), ('VALIDACAO_COORDENADOR', 'Validação do Coordenador'), ('AGENDAMENTO_DEFESA', 'Agendamento de Defesa'), ('DEFESA_REALIZADA', 'Defesa Realizada'), ('AJUSTES_SOLICITADOS', 'Ajustes Solicitados'), ('CONCLUSAO', 'Conclusão'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='tcc',
            name='etapa_atual',
            field=models.CharField(choices=[('INICIALIZACAO', 'Inicialização'), ('DESENVOLVIMENTO', 'Desenvolvimento'), ('FORMACAO_BANCA_FASE_1', 'Formação de Banca - Fase 1'), ('AVALIACAO_FASE_1', 'Avaliação - Fase 1'), ('VALIDACAO_FASE_1', 'Validação - Fase 1'), ('AGENDAMENTO_APRESENTACAO', 'Agendamento da Apresentação'), ('APRESENTACAO_FASE_2', 'Apresentação - Fase 2'), ('APROVADO', 'Aprovado'), ('ANALISE_FINAL_COORDENADOR', 'Análise Final do Coordenador'), ('AGUARDANDO_AJUSTES_FINAIS', 'Aguardando Ajustes Finais'), ('CONCLUIDO', 'Concluído'), ('DESCONTINUADO', 'Descontinuado'), ('REPROVADO_FASE_1', 'Reprovado - Fase 1'), ('REPROVADO_FASE_2', 'Reprovado - Fase 2')], default='INICIALIZACAO', max_length=50, verbose_name='Etapa Atual'),
        ),
    ]
