# Generated by Django 4.2.7 on 2025-10-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tccs', '0013_atualizar_campos_avaliacaofase2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcc',
            name='media_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MF = (NF1 + NF2) / 2', max_digits=5, null=True, verbose_name='Média Final (MF)'),
        ),
        migrations.AddField(
            model_name='tcc',
            name='nf1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Média das avaliações da monografia (Fase I)', max_digits=5, null=True, verbose_name='Nota Final Fase I'),
        ),
        migrations.AddField(
            model_name='tcc',
            name='nf2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Média das avaliações da apresentação (Fase II)', max_digits=5, null=True, verbose_name='Nota Final Fase II'),
        ),
        migrations.AddField(
            model_name='tcc',
            name='resultado_final',
            field=models.CharField(blank=True, choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], help_text='APROVADO se MF >= 6.0, REPROVADO caso contrário', max_length=20, null=True, verbose_name='Resultado Final'),
        ),
    ]
