# Generated by Django 4.2.7 on 2026-02-21 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tccs', '0015_alter_eventotimeline_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaofase1',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('BLOQUEADO', 'Bloqueado'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='avaliacaofase2',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('BLOQUEADO', 'Bloqueado'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='documentotcc',
            name='tipo_documento',
            field=models.CharField(choices=[('PLANO_DESENVOLVIMENTO', 'Plano de Desenvolvimento'), ('TERMO_ACEITE', 'Termo de Aceite'), ('MONOGRAFIA', 'Monografia'), ('MONOGRAFIA_AVALIACAO', 'Monografia para Avaliação (Anônima)'), ('TERMO_SOLICITACAO_AVALIACAO', 'Termo de Solicitação de Avaliação'), ('APRESENTACAO', 'Apresentação'), ('ATA', 'Ata'), ('RELATORIO_AVALIACAO', 'Relatório de Avaliação'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='eventotimeline',
            name='tipo_evento',
            field=models.CharField(choices=[('CRIACAO_TCC', 'Criação do TCC'), ('SOLICITACAO_ENVIADA', 'Solicitação Enviada'), ('SOLICITACAO_ACEITA', 'Solicitação Aceita'), ('SOLICITACAO_RECUSADA', 'Solicitação Recusada'), ('SOLICITACAO_CANCELADA', 'Solicitação Cancelada'), ('UPLOAD_DOCUMENTO', 'Upload de Documento'), ('DOCUMENTO_APROVADO', 'Documento Aprovado'), ('DOCUMENTO_REJEITADO', 'Documento Rejeitado'), ('FEEDBACK_ORIENTADOR', 'Feedback do Orientador'), ('APROVACAO_CONTINUIDADE', 'Aprovação de Continuidade'), ('REPROVACAO_CONTINUIDADE', 'Reprovação de Continuidade'), ('LIBERACAO_AVALIACAO', 'Liberação para Avaliação'), ('FORMACAO_BANCA', 'Formação de Banca'), ('AVALIACAO_ENVIADA', 'Avaliação Enviada'), ('AVALIACAO_REABERTA', 'Avaliação Reaberta'), ('BLOQUEIO_AVALIACOES', 'Bloqueio de Avaliações'), ('DESBLOQUEIO_AVALIACOES', 'Desbloqueio de Avaliações'), ('SOLICITACAO_AJUSTES', 'Solicitação de Ajustes'), ('APROVACAO_PARCIAL', 'Aprovação Parcial'), ('RESULTADO_FASE_1', 'Resultado da Fase I'), ('FASE2_CONCLUIDA', 'Fase II Concluída'), ('RESULTADO_FINAL', 'Resultado Final'), ('VALIDACAO_COORDENADOR', 'Validação do Coordenador'), ('AGENDAMENTO_DEFESA', 'Agendamento de Defesa'), ('DEFESA_REALIZADA', 'Defesa Realizada'), ('AJUSTES_SOLICITADOS', 'Ajustes Solicitados'), ('CONCLUSAO', 'Conclusão'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='tcc',
            name='coorientador',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario__in': ['PROFESSOR', 'COORDENADOR', 'AVALIADOR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tccs_como_coorientador', to=settings.AUTH_USER_MODEL, verbose_name='Coorientador'),
        ),
    ]
