# Generated by Django 4.2.7 on 2026-04-15 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tccs', '0016_add_concluido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaofase1',
            name='avaliador',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario__in': ['PROFESSOR', 'COORDENADOR', 'AVALIADOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador'),
        ),
        migrations.AlterField(
            model_name='avaliacaofase2',
            name='avaliador',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario__in': ['PROFESSOR', 'COORDENADOR', 'AVALIADOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_fase2_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador'),
        ),
        migrations.AlterField(
            model_name='membrobanca',
            name='usuario',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario__in': ['PROFESSOR', 'COORDENADOR', 'AVALIADOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_banca', to=settings.AUTH_USER_MODEL, verbose_name='Membro'),
        ),
    ]
