# Generated by Django 4.2.7 on 2025-10-22 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tccs', '0015_alter_eventotimeline_tipo_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('documento_enviado', 'Documento Enviado'), ('documento_aprovado', 'Documento Aprovado'), ('documento_rejeitado', 'Documento Rejeitado'), ('solicitacao_recebida', 'Solicitação Recebida'), ('solicitacao_aprovada', 'Solicitação Aprovada'), ('solicitacao_rejeitada', 'Solicitação Rejeitada'), ('solicitacao_encaminhada', 'Solicitação Encaminhada'), ('banca_formada', 'Banca Formada'), ('convite_banca', 'Convite para Banca'), ('avaliacao_recebida', 'Avaliação Recebida'), ('avaliacao_fase1_completa', 'Avaliação Fase I Completa'), ('avaliacao_fase2_completa', 'Avaliação Fase II Completa'), ('prazo_proximo', 'Prazo Próximo'), ('prazo_vencido', 'Prazo Vencido'), ('prazo_documento', 'Prazo de Documento'), ('prazo_avaliacao', 'Prazo de Avaliação'), ('etapa_alterada', 'Etapa Alterada'), ('continuidade_aprovada', 'Continuidade Aprovada'), ('continuidade_rejeitada', 'Continuidade Rejeitada'), ('tcc_criado', 'TCC Criado'), ('tcc_concluido', 'TCC Concluído'), ('convite_coorientacao', 'Convite para Coorientação'), ('coorientacao_aceita', 'Coorientação Aceita'), ('coorientacao_recusada', 'Coorientação Recusada'), ('defesa_agendada', 'Defesa Agendada'), ('defesa_alterada', 'Defesa Alterada'), ('defesa_cancelada', 'Defesa Cancelada'), ('ajustes_solicitados', 'Ajustes Solicitados'), ('ajustes_aprovados', 'Ajustes Aprovados'), ('mensagem_sistema', 'Mensagem do Sistema'), ('alerta_coordenador', 'Alerta ao Coordenador')], max_length=50, verbose_name='Tipo de Notificação')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('action_url', models.CharField(blank=True, help_text='URL para onde o usuário será direcionado ao clicar na notificação', max_length=255, null=True, verbose_name='URL de Ação')),
                ('metadata', models.JSONField(blank=True, help_text='Dados adicionais da notificação em formato JSON', null=True, verbose_name='Metadados')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('lido_em', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
                ('tcc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='tccs.tcc', verbose_name='TCC Relacionado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario', '-criado_em'], name='notificacoe_usuario_f049a9_idx'), models.Index(fields=['usuario', 'lida'], name='notificacoe_usuario_a5894e_idx'), models.Index(fields=['tcc'], name='notificacoe_tcc_id_81d88f_idx')],
            },
        ),
    ]
