# Generated by Django 4.2.7 on 2025-10-23 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('documento_enviado', 'Documento Enviado'), ('documento_aprovado', 'Documento Aprovado'), ('documento_rejeitado', 'Documento Rejeitado'), ('solicitacao_recebida', 'Solicitação Recebida'), ('solicitacao_aprovada', 'Solicitação Aprovada'), ('solicitacao_rejeitada', 'Solicitação Rejeitada'), ('solicitacao_encaminhada', 'Solicitação Encaminhada'), ('banca_formada', 'Banca Formada'), ('banca_definida', 'Banca Definida'), ('convite_banca', 'Convite para Banca'), ('avaliacao_recebida', 'Avaliação Recebida'), ('avaliacao_aprovada', 'Avaliação Aprovada'), ('avaliacao_fase1_completa', 'Avaliação Fase I Completa'), ('avaliacao_fase2_completa', 'Avaliação Fase II Completa'), ('resultado_fase_1', 'Resultado Fase I'), ('resultado_final', 'Resultado Final'), ('prazo_proximo', 'Prazo Próximo'), ('prazo_vencido', 'Prazo Vencido'), ('prazo_documento', 'Prazo de Documento'), ('prazo_avaliacao', 'Prazo de Avaliação'), ('etapa_alterada', 'Etapa Alterada'), ('continuidade_aprovada', 'Continuidade Aprovada'), ('continuidade_rejeitada', 'Continuidade Rejeitada'), ('tcc_criado', 'TCC Criado'), ('tcc_concluido', 'TCC Concluído'), ('convite_coorientacao', 'Convite para Coorientação'), ('coorientacao_aceita', 'Coorientação Aceita'), ('coorientacao_recusada', 'Coorientação Recusada'), ('defesa_agendada', 'Defesa Agendada'), ('defesa_alterada', 'Defesa Alterada'), ('defesa_cancelada', 'Defesa Cancelada'), ('ajustes_solicitados', 'Ajustes Solicitados'), ('ajustes_aprovados', 'Ajustes Aprovados'), ('mensagem_sistema', 'Mensagem do Sistema'), ('alerta_coordenador', 'Alerta ao Coordenador')], max_length=50, verbose_name='Tipo de Notificação'),
        ),
        migrations.CreateModel(
            name='PreferenciasEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_aceitar_convite_orientador', models.BooleanField(default=True, help_text='Notificar quando solicitação de orientação for aprovada', verbose_name='Aceitar convite de orientador')),
                ('aluno_ajuste_monografia', models.BooleanField(default=True, help_text='Notificar quando orientador solicitar ajustes na monografia', verbose_name='Ajuste de monografia solicitado')),
                ('aluno_termo_disponivel', models.BooleanField(default=True, help_text='Notificar quando coordenador disponibilizar termo de solicitação', verbose_name='Termo de solicitação disponível')),
                ('aluno_continuidade_aprovada', models.BooleanField(default=True, help_text='Notificar sobre decisão de continuidade do orientador', verbose_name='Continuidade aprovada/rejeitada')),
                ('aluno_resultado_fase_1', models.BooleanField(default=True, help_text='Notificar quando resultado da Fase I estiver disponível', verbose_name='Resultado Fase I')),
                ('aluno_agendamento_defesa', models.BooleanField(default=True, help_text='Notificar quando defesa for agendada', verbose_name='Agendamento de defesa')),
                ('aluno_finalizacao_tcc', models.BooleanField(default=True, help_text='Notificar quando TCC for finalizado', verbose_name='Finalização do TCC')),
                ('prof_receber_monografia', models.BooleanField(default=True, help_text='Notificar quando orientando enviar monografia', verbose_name='Receber monografia')),
                ('prof_continuidade_aprovada', models.BooleanField(default=True, help_text='Notificar quando aprovar/rejeitar continuidade', verbose_name='Continuidade aprovada')),
                ('prof_lembrete_termo', models.BooleanField(default=True, help_text='Notificar sobre prazos de termo de solicitação', verbose_name='Lembrete de termo')),
                ('prof_resultado_fase_1', models.BooleanField(default=True, help_text='Notificar quando todas avaliações da Fase I forem concluídas', verbose_name='Resultado Fase I')),
                ('prof_finalizacao_tcc', models.BooleanField(default=True, help_text='Notificar quando TCC de orientando for finalizado', verbose_name='Finalização do TCC')),
                ('coord_convite_aluno', models.BooleanField(default=True, help_text='Notificar quando aluno solicitar orientação', verbose_name='Convite de aluno')),
                ('coord_monografia_aprovada', models.BooleanField(default=True, help_text='Notificar quando orientador aprovar monografia', verbose_name='Monografia aprovada')),
                ('coord_termo_enviado', models.BooleanField(default=True, help_text='Notificar quando aluno enviar termo de solicitação', verbose_name='Termo enviado')),
                ('coord_continuidade_aprovada', models.BooleanField(default=True, help_text='Notificar quando orientador aprovar/rejeitar continuidade', verbose_name='Continuidade aprovada')),
                ('coord_avaliacoes_fase1_completas', models.BooleanField(default=True, help_text='Notificar quando todas avaliações da Fase I forem enviadas', verbose_name='Avaliações Fase I completas')),
                ('coord_avaliacoes_fase2_completas', models.BooleanField(default=True, help_text='Notificar quando todas avaliações da Fase II forem enviadas', verbose_name='Avaliações Fase II completas')),
                ('coord_defesa_agendada', models.BooleanField(default=True, help_text='Notificar quando defesa for agendada', verbose_name='Defesa agendada')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_email', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Preferência de E-mail',
                'verbose_name_plural': 'Preferências de E-mail',
            },
        ),
    ]
