# Generated by Django 4.2.7 on 2025-10-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_alter_notificacao_tipo_preferenciasemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('documento_enviado', 'Documento Enviado'), ('documento_aprovado', 'Documento Aprovado'), ('documento_rejeitado', 'Documento Rejeitado'), ('termo_enviado', 'Termo Enviado'), ('solicitacao_recebida', 'Solicitação Recebida'), ('solicitacao_aprovada', 'Solicitação Aprovada'), ('solicitacao_rejeitada', 'Solicitação Rejeitada'), ('solicitacao_encaminhada', 'Solicitação Encaminhada'), ('convite_aluno', 'Convite de Aluno'), ('banca_formada', 'Banca Formada'), ('banca_definida', 'Banca Definida'), ('convite_banca', 'Convite para Banca'), ('avaliacao_recebida', 'Avaliação Recebida'), ('avaliacao_aprovada', 'Avaliação Aprovada'), ('avaliacao_fase1_completa', 'Avaliação Fase I Completa'), ('avaliacao_fase2_completa', 'Avaliação Fase II Completa'), ('resultado_fase_1', 'Resultado Fase I'), ('resultado_fase_2', 'Resultado Fase II'), ('resultado_final', 'Resultado Final'), ('prazo_proximo', 'Prazo Próximo'), ('prazo_vencido', 'Prazo Vencido'), ('prazo_documento', 'Prazo de Documento'), ('prazo_avaliacao', 'Prazo de Avaliação'), ('etapa_alterada', 'Etapa Alterada'), ('continuidade_aprovada', 'Continuidade Aprovada'), ('continuidade_rejeitada', 'Continuidade Rejeitada'), ('tcc_criado', 'TCC Criado'), ('tcc_concluido', 'TCC Concluído'), ('convite_coorientacao', 'Convite para Coorientação'), ('coorientacao_aceita', 'Coorientação Aceita'), ('coorientacao_recusada', 'Coorientação Recusada'), ('defesa_agendada', 'Defesa Agendada'), ('defesa_alterada', 'Defesa Alterada'), ('defesa_cancelada', 'Defesa Cancelada'), ('ajustes_solicitados', 'Ajustes Solicitados'), ('ajustes_aprovados', 'Ajustes Aprovados'), ('mensagem_sistema', 'Mensagem do Sistema'), ('alerta_coordenador', 'Alerta ao Coordenador')], max_length=50, verbose_name='Tipo de Notificação'),
        ),
    ]
