# Generated by Django 4.2.7 on 2026-02-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0003_alter_notificacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasemail',
            name='prof_convite_orientacao',
            field=models.BooleanField(default=True, help_text='Notificar quando orientação ou co-orientação for aprovada', verbose_name='Convite de orientação'),
        ),
        migrations.AlterField(
            model_name='preferenciasemail',
            name='aluno_aceitar_convite_orientador',
            field=models.BooleanField(default=True, help_text='Notificar quando solicitação de orientação for analisada', verbose_name='Convite de orientação'),
        ),
    ]
