# Generated by Django 4.2.7 on 2026-02-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0004_preferenciasemail_prof_convite_orientacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasemail',
            name='aval_continuidade_aprovada',
            field=models.BooleanField(default=True, help_text='Notificar 1 dia antes da confirmação de continuidade', verbose_name='Lembrete de aprovação de continuidade'),
        ),
        migrations.AddField(
            model_name='preferenciasemail',
            name='aval_convite_orientacao',
            field=models.BooleanField(default=True, help_text='Notificar quando co-orientação for aprovada', verbose_name='Convite de co-orientação'),
        ),
        migrations.AddField(
            model_name='preferenciasemail',
            name='aval_finalizacao_tcc',
            field=models.BooleanField(default=True, help_text='Notificar quando TCC de co-orientando for finalizado', verbose_name='Finalização do TCC'),
        ),
        migrations.AddField(
            model_name='preferenciasemail',
            name='aval_lembrete_termo',
            field=models.BooleanField(default=True, help_text='Notificar 1 dia antes do prazo limite de envio do termo de solicitação de avaliação', verbose_name='Lembrete de envio de termo de solicitação de avaliação'),
        ),
        migrations.AddField(
            model_name='preferenciasemail',
            name='aval_participacao_banca',
            field=models.BooleanField(default=True, help_text='Notificar quando for adicionado a uma banca', verbose_name='Participação em banca'),
        ),
        migrations.AddField(
            model_name='preferenciasemail',
            name='aval_receber_monografia',
            field=models.BooleanField(default=True, help_text='Notificar quando orientando enviar monografia', verbose_name='Receber monografia'),
        ),
        migrations.AddField(
            model_name='preferenciasemail',
            name='aval_resultado_fase_1',
            field=models.BooleanField(default=True, help_text='Notificar quando todas avaliações da Fase I forem concluídas', verbose_name='Resultado Fase I'),
        ),
        migrations.AddField(
            model_name='preferenciasemail',
            name='prof_participacao_banca',
            field=models.BooleanField(default=True, help_text='Notificar quando for adicionado a uma banca', verbose_name='Participação em banca'),
        ),
        migrations.AlterField(
            model_name='preferenciasemail',
            name='prof_continuidade_aprovada',
            field=models.BooleanField(default=True, help_text='Notificar 1 dia antes da confirmação de continuidade', verbose_name='Lembrete de aprovação de continuidade'),
        ),
        migrations.AlterField(
            model_name='preferenciasemail',
            name='prof_convite_orientacao',
            field=models.BooleanField(default=True, help_text='Notificar quando orientação for aprovada', verbose_name='Convite de orientação'),
        ),
        migrations.AlterField(
            model_name='preferenciasemail',
            name='prof_lembrete_termo',
            field=models.BooleanField(default=True, help_text='Notificar 1 dia antes do prazo limite de envio do termo de solicitação de avaliação', verbose_name='Lembrete de envio de termo de solicitação de avaliação'),
        ),
    ]
