# Generated by Django 4.2.7 on 2026-02-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0005_preferenciasemail_aval_continuidade_aprovada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferenciasemail',
            name='aval_continuidade_aprovada',
        ),
        migrations.RemoveField(
            model_name='preferenciasemail',
            name='aval_lembrete_termo',
        ),
    ]
