# Generated by Django 4.2.7 on 2026-02-17 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_avisos', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='avisos.aviso', verbose_name='Aviso')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['criado_em'],
            },
        ),
    ]
