# Generated by Django 4.2.7 on 2026-02-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0002_comentarioaviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='cor',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cor do card'),
        ),
    ]
