# Generated by Django 4.2.16 on 2025-10-04 21:05

from django.db import migrations


def copiar_codigos(apps, schema_editor):
    """Copia dados de users_codigocadastro para definicoes_codigocadastro."""
    # Usar conexão direta ao banco para copiar dados entre tabelas
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            INSERT INTO definicoes_codigocadastro (id, tipo, codigo, atualizado_em, atualizado_por_id)
            SELECT id, tipo, codigo, atualizado_em, atualizado_por_id
            FROM users_codigocadastro
        """)


def reverter_copia(apps, schema_editor):
    """Remove dados copiados em caso de rollback."""
    CodigoCadastro = apps.get_model('definicoes', 'CodigoCadastro')
    CodigoCadastro.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('definicoes', '0001_initial'),
        ('users', '0002_alunoproxy_avaliadorproxy_coordenadorproxy_and_more'),
    ]

    operations = [
        migrations.RunPython(copiar_codigos, reverter_copia),
    ]
