# Generated by Django 4.2.7 on 2025-10-13 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('definicoes', '0002_copiar_codigos_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=10, verbose_name='Semestre')),
                ('inicio_periodo_letivo', models.DateField(blank=True, null=True, verbose_name='Início do Período Letivo')),
                ('envio_documentos_fim', models.DateField(blank=True, null=True, verbose_name='Prazo final para envio de documentos iniciais')),
                ('avaliacao_continuidade_fim', models.DateField(blank=True, null=True, verbose_name='Prazo final para avaliação de continuidade')),
                ('submissao_monografia_fim', models.DateField(blank=True, null=True, verbose_name='Prazo final para submissão da monografia')),
                ('avaliacao_fase1_inicio', models.DateField(blank=True, null=True, verbose_name='Início da Avaliação Fase I')),
                ('avaliacao_fase1_fim', models.DateField(blank=True, null=True, verbose_name='Prazo final da Avaliação Fase I')),
                ('defesas_inicio', models.DateField(blank=True, null=True, verbose_name='Início do Período de Defesas')),
                ('defesas_fim', models.DateField(blank=True, null=True, verbose_name='Prazo final do Período de Defesas')),
                ('ajustes_finais_fim', models.DateField(blank=True, null=True, verbose_name='Prazo final para Ajustes Finais')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendario_atualizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendário do Semestre',
                'verbose_name_plural': 'Calendários de Semestre',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
