# Generated by Django 4.2.7 on 2025-10-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definicoes', '0003_calendariosemestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendariosemestre',
            name='peso_conclusoes',
            field=models.DecimalField(decimal_places=1, default=1.5, max_digits=3, verbose_name='Peso - Conclusões'),
        ),
        migrations.AddField(
            model_name='calendariosemestre',
            name='peso_desenvolvimento',
            field=models.DecimalField(decimal_places=1, default=3.5, max_digits=3, verbose_name='Peso - Desenvolvimento'),
        ),
        migrations.AddField(
            model_name='calendariosemestre',
            name='peso_introducao',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=3, verbose_name='Peso - Introdução/Relevância'),
        ),
        migrations.AddField(
            model_name='calendariosemestre',
            name='peso_resumo',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='Peso - Resumo'),
        ),
        migrations.AddField(
            model_name='calendariosemestre',
            name='peso_revisao',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=3, verbose_name='Peso - Revisão Bibliográfica'),
        ),
    ]
