# Generated by Django 4.2.7 on 2025-10-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definicoes', '0005_renomear_campos_peso_fase2'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendariosemestre',
            name='peso_clareza_fluencia',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=3, verbose_name='Peso - Clareza e Fluência Verbal'),
        ),
        migrations.AddField(
            model_name='calendariosemestre',
            name='peso_coerencia_conteudo',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=3, verbose_name='Peso - Coerência do Conteúdo'),
        ),
        migrations.AddField(
            model_name='calendariosemestre',
            name='peso_dominio_tema',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=3, verbose_name='Peso - Domínio e Conhecimento do Tema'),
        ),
        migrations.AddField(
            model_name='calendariosemestre',
            name='peso_observancia_tempo',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='Peso - Observância do Tempo de Apresentação'),
        ),
        migrations.AddField(
            model_name='calendariosemestre',
            name='peso_qualidade_apresentacao',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=3, verbose_name='Peso - Qualidade e Estrutura da Apresentação'),
        ),
    ]
