# Generated by Django 4.2.7 on 2025-10-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definicoes', '0006_calendariosemestre_peso_clareza_fluencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendariosemestre',
            name='avaliacao_fase1_inicio',
        ),
        migrations.RemoveField(
            model_name='calendariosemestre',
            name='defesas_inicio',
        ),
        migrations.RemoveField(
            model_name='calendariosemestre',
            name='inicio_periodo_letivo',
        ),
        migrations.AlterField(
            model_name='calendariosemestre',
            name='avaliacao_fase1_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Avaliação - Fase I'),
        ),
        migrations.AlterField(
            model_name='calendariosemestre',
            name='defesas_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Apresentação dos trabalhos (Fase II)'),
        ),
    ]
