# Generated by Django 4.2.7 on 2025-10-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definicoes', '0007_remove_calendariosemestre_avaliacao_fase1_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendariosemestre',
            name='preparacao_bancas_fase1_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Preparação das bancas (Fase I) - Fim'),
        ),
        migrations.AddField(
            model_name='calendariosemestre',
            name='preparacao_bancas_fase1_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Preparação das bancas (Fase I) - Início'),
        ),
        migrations.AddField(
            model_name='calendariosemestre',
            name='preparacao_bancas_fase2',
            field=models.DateField(blank=True, null=True, verbose_name='Preparação das bancas (Fase II)'),
        ),
        migrations.AddField(
            model_name='calendariosemestre',
            name='reuniao_alunos',
            field=models.DateField(blank=True, help_text='Orientações gerais sobre o desenvolvimento do TCC', null=True, verbose_name='Reunião com alunos'),
        ),
    ]
