# Generated by Django 4.2.7 on 2025-10-19 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('definicoes', '0008_adicionar_datas_informativas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ORIENTACOES_GERAIS', 'Orientações gerais sobre o TCC'), ('TERMO_ACEITE', 'Termo de Aceite de Orientação'), ('PLANO_DESENVOLVIMENTO', 'Plano de Desenvolvimento'), ('TEMPLATE_WORD', 'Template Word - TCC'), ('ABNT_BIBLIOGRAFIA', 'ABNT - Estilo de bibliografia do Word'), ('ABNT_BIBLIOGRAFIA_2018', 'ABNT - Estilo de bibliografia do Word 2018')], max_length=50, unique=True, verbose_name='Tipo de Documento')),
                ('arquivo', models.FileField(upload_to='documentos_referencia/', verbose_name='Arquivo')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_atualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Referência',
                'verbose_name_plural': 'Documentos de Referência',
                'ordering': ['tipo'],
            },
        ),
    ]
