# Generated by Django 4.2.7 on 2025-10-23 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('definicoes', '0009_documentoreferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False, help_text='Ativa/desativa o envio de e-mails pelo sistema', verbose_name='E-mail habilitado')),
                ('email_host', models.CharField(default='smtp.gmail.com', help_text='Endereço do servidor SMTP', max_length=255, verbose_name='Servidor SMTP')),
                ('email_port', models.IntegerField(default=587, help_text='Porta do servidor SMTP', verbose_name='Porta SMTP')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Ativa criptografia TLS para conexão SMTP', verbose_name='Usar TLS')),
                ('email_host_user', models.EmailField(blank=True, help_text='Endereço de e-mail usado para enviar mensagens', max_length=255, verbose_name='E-mail do remetente')),
                ('email_host_password', models.CharField(blank=True, help_text='Senha de app do Gmail (será criptografada)', max_length=500, verbose_name='Senha de app')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_email_atualizada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de E-mail',
                'verbose_name_plural': 'Configurações de E-mail',
            },
        ),
    ]
