# Generated by Django 4.2.7 on 2025-11-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definicoes', '0010_configuracaoemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendariosemestre',
            name='avaliacao_continuidade_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início da janela de confirmação de continuidade'),
        ),
    ]
