# Generated by Django 4.2.16 on 2025-10-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.usuario',),
        ),
        migrations.CreateModel(
            name='AvaliadorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Avaliador Externo',
                'verbose_name_plural': 'Avaliadores Externos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.usuario',),
        ),
        migrations.CreateModel(
            name='CoordenadorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.usuario',),
        ),
        migrations.CreateModel(
            name='ProfessorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.usuario',),
        ),
        migrations.AlterModelOptions(
            name='codigocadastro',
            options={'ordering': ['tipo'], 'verbose_name': 'Codigo de Cadastro', 'verbose_name_plural': 'Codigos de Cadastro'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='codigocadastro',
            name='codigo',
            field=models.CharField(max_length=100, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='afiliacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Afiliacao'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='curso',
            field=models.CharField(blank=True, choices=[('ENGENHARIA_ELETRICA', 'Engenharia Eletrica'), ('ENGENHARIA_CONTROLE_AUTOMACAO', 'Engenharia de Controle e Automacao')], max_length=50, null=True, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('AVALIADOR', 'Avaliador Externo'), ('COORDENADOR', 'Coordenador')], max_length=20, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tratamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tratamento'),
        ),
        migrations.DeleteModel(
            name='PerfilProfessor',
        ),
    ]
