# Generated by Django 4.2.16 on 2025-10-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alunoproxy_avaliadorproxy_coordenadorproxy_and_more'),
        ('definicoes', '0002_copiar_codigos_cadastro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodigoCadastro',
        ),
    ]
