# Generated by Django 4.2.16 on 2025-10-05 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_codigocadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasVisuais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('dark', 'Dark'), ('sigaa', 'SIGAA')], default='white', max_length=10, verbose_name='Tema')),
                ('tamanho_fonte', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Medio'), ('grande', 'Grande')], default='medio', max_length=10, verbose_name='Tamanho da Fonte')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_visuais', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencias Visuais',
                'verbose_name_plural': 'Preferencias Visuais',
            },
        ),
    ]
