# Generated by Django 4.2.16 on 2025-10-05 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_preferenciasvisuais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
    ]
