# Generated by Django 4.2.16 on 2025-10-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_usuario_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='afiliacao',
            field=models.CharField(blank=True, choices=[('Universidade Federal de Pernambuco', 'Universidade Federal de Pernambuco'), ('UFRPE', 'UFRPE'), ('IFPE', 'IFPE'), ('Outra Instituição', 'Outra Instituição')], max_length=200, null=True, verbose_name='Afiliacao'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(blank=True, choices=[('Departamento de Engenharia Elétrica', 'Departamento de Engenharia Elétrica'), ('Departamento de Controle e Automação', 'Departamento de Controle e Automação'), ('Departamento Acadêmico de Computação', 'Departamento Acadêmico de Computação')], max_length=200, null=True, verbose_name='Departamento'),
        ),
    ]
