# Generated by Django 4.2.16 on 2025-10-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usuario_afiliacao_alter_usuario_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='afiliacao_customizada',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Afiliacao Customizada'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tratamento_customizado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tratamento Customizado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='afiliacao',
            field=models.CharField(blank=True, choices=[('Universidade Federal de Pernambuco', 'Universidade Federal de Pernambuco'), ('UFRPE', 'UFRPE'), ('IFPE', 'IFPE'), ('Outro', 'Outro')], max_length=200, null=True, verbose_name='Afiliacao'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(blank=True, choices=[('Departamento de Engenharia Elétrica', 'Departamento de Engenharia Elétrica'), ('Departamento de Controle e Automação', 'Departamento de Controle e Automação')], max_length=200, null=True, verbose_name='Departamento'),
        ),
    ]
