# Generated by Django 4.2.16 on 2025-10-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usuario_afiliacao_customizada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tratamento',
            field=models.CharField(blank=True, choices=[('Prof. Dr.', 'Prof. Dr.'), ('Prof. Ms.', 'Prof. Ms.'), ('Prof.', 'Prof.'), ('Dr.', 'Dr.'), ('Eng.', 'Eng.'), ('Outro', 'Outro')], max_length=50, null=True, verbose_name='Tratamento'),
        ),
    ]
