# Generated by Django 4.2.16 on 2025-10-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usuario_tratamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(blank=True, choices=[('Departamento de Engenharia Eletrica', 'Departamento de Engenharia Eletrica'), ('Departamento de Controle e Automacao', 'Departamento de Controle e Automacao')], max_length=200, null=True, verbose_name='Departamento'),
        ),
    ]
