# Generated by Django 4.2.16 on 2025-10-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usuario_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(blank=True, choices=[('Departamento de Engenharia Elétrica', 'Departamento de Engenharia Elétrica'), ('Departamento de Controle e Automação', 'Departamento de Controle e Automação')], max_length=200, null=True, verbose_name='Departamento'),
        ),
    ]
